/* Creacion Tablas Modelo SERVICIOS */  
USE ODS; 
 
DROP TABLE IF EXISTS ODS_DM_PRODUCTOS; 
CREATE TABLE IF NOT EXISTS ODS_DM_PRODUCTOS ( 
    ID_PRODUCTO INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY, 
    DE_PRODUCTO VARCHAR(512), 
    FC_INSERT DATETIME, 
    FC_MODIFICACION DATETIME); 
     
DROP TABLE IF EXISTS ODS_DM_CANALES; 
CREATE TABLE IF NOT EXISTS ODS_DM_CANALES ( 
    ID_CANAL INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY, 
    DE_CANAL VARCHAR(512), 
    FC_INSERT DATETIME, 
    FC_MODIFICACION DATETIME); 
 
DROP TABLE IF EXISTS ODS_HC_SERVICIOS; 
CREATE TABLE IF NOT EXISTS ODS_HC_SERVICIOS ( 
    ID_SERVICIO INT(11) UNSIGNED NOT NULL PRIMARY KEY, 
    ID_CLIENTE INT(11), 
    FLG_CLIENTE_EXISTENTE TINYINT(1) 
    ID_PRODUCTO INT, 
    PUNTO_ACCESO VARCHAR(512), 
    ID_CANAL INT, 
    ID_AGENTE INT(11), 
    ID_DIRECCION_SERVICIO INT, 
    FC_INICIO DATETIME, 
    FC_INSTALACION DATETIME, 
    FC_FIN DATETIME, 
    FC_INSERT DATETIME, 
    FC_MODIFICACION DATETIME); 