/* Añadir Indices y Claves Ajenas de Servicios */ 
USE ODS; 
 
ALTER TABLE ODS_HC_SERVICIOS MODIFY COLUMN ID_PRODUCTO INT(10) UNSIGNED; 
ALTER TABLE ODS_HC_SERVICIOS ADD INDEX fk_serv_prod_idx (ID_PRODUCTO ASC); 
ALTER TABLE ODS_HC_SERVICIOS ADD CONSTRAINT fk_serv_prod FOREIGN KEY (ID_PRODUCTO) 
REFERENCES ODS_DM_PRODUCTOS (ID_PRODUCTO); 
 
ALTER TABLE ODS_HC_SERVICIOS MODIFY COLUMN ID_CANAL INT(10) UNSIGNED; 
ALTER TABLE ODS_HC_SERVICIOS ADD INDEX fk_serv_can_idx (ID_CANAL ASC); 
ALTER TABLE ODS_HC_SERVICIOS ADD CONSTRAINT fk_serv_can FOREIGN KEY (ID_CANAL) 
REFERENCES ODS_DM_CANALES (ID_CANAL); 
 
ALTER TABLE ODS_HC_SERVICIOS MODIFY COLUMN ID_DIRECCION_SERVICIO INT(10) UNSIGNED; 
ALTER TABLE ODS_HC_SERVICIOS ADD INDEX fk_serv_dir_idx (ID_DIRECCION_SERVICIO ASC); 
ALTER TABLE ODS_HC_SERVICIOS ADD CONSTRAINT fk_serv_dir FOREIGN KEY (ID_DIRECCION_SERVICIO) 
REFERENCES ODS_HC_DIRECCIONES (ID_DIRECCION); 
 
ALTER TABLE ODS_HC_SERVICIOS MODIFY COLUMN ID_CLIENTE INT(11); 
ALTER TABLE ODS_HC_SERVICIOS ADD INDEX fk_serv_cli_idx (ID_CLIENTE ASC); 
ALTER TABLE ODS_HC_SERVICIOS ADD CONSTRAINT fk_serv_cli FOREIGN KEY (ID_CLIENTE) 
REFERENCES ODS_HC_CLIENTES (ID_CLIENTE); 