/* Insertar Valores Clientes */ 
USE ODS; 

INSERT INTO ODS_HC_CLIENTES 
SELECT CUSTOMER_ID AS ID_CLIENTE, 
    CASE WHEN LENGTH(TRIM(FIRST_NAME)) <> 0 THEN TRIM(UPPER(FIRST_NAME)) ELSE 'DESCONOCIDO' END NOMBRE_CLIENTE, 
    CASE WHEN LENGTH(TRIM(LAST_NAME)) <> 0 THEN TRIM(UPPER(LAST_NAME)) ELSE 'DESCONOCIDO' END APELLIDOS_CLIENTE, 
    CASE WHEN LENGTH(TRIM(IDENTIFIED_DOC)) <> 0 THEN TRIM(UPPER(IDENTIFIED_DOC)) ELSE '99-999-9999' END NUMDOC_CLIENTE, 
    ID_SEXO, 
    CASE WHEN LENGTH(TRIM(DIR.ID_DIRECCION)) <> 0 THEN TRIM(UPPER(DIR.ID_DIRECCION)) ELSE 999999 END ID_DIRECCION, 
    CASE WHEN LENGTH(TRIM(PHONE)) <> 0 THEN CONVERT(TRIM(REPLACE(PHONE,'-','')), UNSIGNED INTEGER) ELSE 9999999999 END TELEFONO_CLIENTE, 
    CASE WHEN LENGTH(TRIM(EMAIL)) <> 0 THEN TRIM(UPPER(EMAIL)) ELSE 'DESCONOCIDO' END EMAIL, 
    CASE WHEN LENGTH(TRIM(BIRTHDAY)) <> 0 THEN STR_TO_DATE(BIRTHDAY, '%d/%m/%Y') ELSE STR_TO_DATE('31/12/9999', '%d/%m/%Y') END FC_NACIMIENTO, 
    PROF.ID_PROFESION, 
    COMP.ID_COMPANYA, 
    NOW(), 
    STR_TO_DATE('31/12/9999', '%d/%m/%Y') 
FROM STAGE.STG_CLIENTES_CRM CLIENTES 
    INNER JOIN ODS.ODS_DM_SEXOS SEXO ON CASE WHEN LENGTH(TRIM(GENDER)) <> 0 THEN UPPER(TRIM(CLIENTES.GENDER)) ELSE 'DESCONOCIDO' END=SEXO.DE_SEXO 
    INNER JOIN ODS.ODS_DM_PROFESIONES PROF ON CASE WHEN LENGTH(TRIM(PROFESION)) <> 0 THEN UPPER(TRIM(CLIENTES.PROFESION)) ELSE 'NO APLICA' END=PROF.DE_PROFESION 
    INNER JOIN ODS.ODS_DM_COMPANYAS COMP ON CASE WHEN LENGTH(TRIM(COMPANY)) <> 0 THEN UPPER(TRIM(CLIENTES.COMPANY)) ELSE 'DESCONOCIDO' END=COMP.DE_COMPANYA 
    LEFT OUTER JOIN ODS.TMP_DIRECCIONES_CLIENTES2 DIR ON DIR.ID_CLIENTE = CLIENTES.CUSTOMER_ID; 
COMMIT; 
INSERT INTO ODS.ODS_HC_CLIENTES 
VALUES (999999, 'DESCONOCIDO', 'DESCONOCIDO', '99-999-9999', 99, 999999, 9999999999, 'DESCONOCIDO', STR_TO_DATE('31/12/9999', '%d/%m/%Y'), 999,  999,  NOW(),  NOW()); 
INSERT INTO ODS.ODS_HC_CLIENTES 
VALUES (999998, 'NO APLICA', 'NO APLICA', '99-999-9998', 98, 999998, 9999999998, 'NO APLICA', STR_TO_DATE('31/12/9998', '%d/%m/%Y'), 998,  998,  NOW(),  NOW()); 
COMMIT; 
ANALYZE TABLE ODS_HC_CLIENTES; 
 
DROP TABLE IF EXISTS TMP_DIRECCIONES_CLIENTES; 
DROP TABLE IF EXISTS TMP_DIRECCIONES_CLIENTES2; 
COMMIT; 