/* Creacion Indices y Claves ajenas Modelo LLAMADAS */ 
USE ODS; 
 
ALTER TABLE ODS_HC_LLAMADAS MODIFY COLUMN ID_CLIENTE INT(11); 
ALTER TABLE ODS_HC_LLAMADAS ADD INDEX fk_llam_cli_idx (ID_CLIENTE ASC); 
ALTER TABLE ODS_HC_LLAMADAS ADD CONSTRAINT fk_llam_cli FOREIGN KEY (ID_CLIENTE) 
REFERENCES ODS_HC_CLIENTES (ID_CLIENTE); 
 
ALTER TABLE ODS_HC_LLAMADAS MODIFY COLUMN ID_DEPARTAMENTO_CC INT(10); 
ALTER TABLE ODS_HC_LLAMADAS ADD INDEX fk_llam_dep_idx (ID_DEPARTAMENTO_CC ASC); 
ALTER TABLE ODS_HC_LLAMADAS ADD CONSTRAINT fk_llam_dep FOREIGN KEY (ID_DEPARTAMENTO_CC) 
REFERENCES ODS_DM_DEPARTAMENTOS_CC (ID_DEPARTAMENTO_CC); 
 
ALTER TABLE ODS_HC_LLAMADAS MODIFY COLUMN ID_AGENTE_CC INT(10); 
ALTER TABLE ODS_HC_LLAMADAS ADD INDEX fk_llam_age_idx (ID_AGENTE_CC ASC); 
ALTER TABLE ODS_HC_LLAMADAS ADD CONSTRAINT fk_llam_age FOREIGN KEY (ID_AGENTE_CC) 
REFERENCES ODS_DM_AGENTES_CC (ID_AGENTE_CC); 