/* Insertar Valores en Modelo LLAMADAS */
USE ODS; 
 
INSERT INTO ODS_DM_DEPARTAMENTOS_CC (DE_DEPARTAMENTO_CC, FC_INSERT, FC_MODIFICACION) 
SELECT DISTINCT UPPER(TRIM(SERVICE)), NOW(), NOW() 
FROM STAGE.STG_CONTACTOS_IVR 
WHERE LENGTH(TRIM(SERVICE)) <> 0; 
COMMIT; 
INSERT INTO ODS_DM_DEPARTAMENTOS_CC VALUES (99, 'DESCONOCIDO', NOW(), NOW()); 
INSERT INTO ODS_DM_DEPARTAMENTOS_CC VALUES (98, 'NO APLICA', NOW(), NOW()); 
COMMIT; 
ANALYZE TABLE ODS_DM_DEPARTAMENTOS_CC; 
 
INSERT INTO ODS_DM_AGENTES_CC (DE_AGENTE_CC, FC_INSERT, FC_MODIFICACION) 
    SELECT DISTINCT UPPER(TRIM(AGENT)), NOW(), NOW() 
    FROM STAGE.STG_CONTACTOS_IVR 
    WHERE LENGTH(TRIM(AGENT)) <> 0; 
COMMIT; 
INSERT INTO ODS_DM_AGENTES_CC VALUES (999, 'DESCONOCIDO', NOW(), NOW()); 
INSERT INTO ODS_DM_AGENTES_CC VALUES (998, 'NO APLICA', NOW(), NOW()); 
COMMIT; 
ANALYZE TABLE ODS_DM_AGENTES_CC; 