/* Insertar Datos en modelo FACTURAS */ 
USE ODS; 
 
INSERT INTO ODS_DM_METODOS_PAGO (DE_METODO_PAGO, FC_INSERT, FC_MODIFICACION) 
    SELECT DISTINCT UPPER(TRIM(BILL_METHOD)), NOW(), NOW() 
    FROM STAGE.STG_FACTURAS_FCT 
    WHERE LENGTH(TRIM(BILL_METHOD)) <> 0; 
COMMIT; 
INSERT INTO ODS_DM_METODOS_PAGO VALUES (99, 'DESCONOCIDO', NOW(), NOW()); 
INSERT INTO ODS_DM_METODOS_PAGO VALUES (98, 'NO APLICA', NOW(), NOW()); 
COMMIT; 
ANALYZE TABLE ODS_DM_METODOS_PAGO; 
 
INSERT INTO ODS_DM_CICLOS_FACTURACION (DE_CICLO_FACTURACION, FC_INSERT, FC_MODIFICACION) 
    SELECT DISTINCT UPPER(TRIM(BILL_CYCLE)), NOW(), NOW() 
    FROM STAGE.STG_FACTURAS_FCT 
    WHERE LENGTH(TRIM(BILL_CYCLE)) <> 0; 
COMMIT; 
INSERT INTO ODS_DM_CICLOS_FACTURACION VALUES (99, 'DESCONOCIDO', NOW(), NOW()); 
INSERT INTO ODS_DM_CICLOS_FACTURACION VALUES (98, 'NO APLICA', NOW(), NOW()); 
COMMIT; 
ANALYZE TABLE ODS_DM_CICLOS_FACTURACION; 
USE ODS; 